
import type { Metadata } from "next";
import { Geist, Geist_Mono , Inter} from "next/font/google";
import "../../app/globals.css";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
      import { BadgeCheckIcon, ChevronRightIcon , Mail , Newspaper , Blocks , TextWrap , Settings} from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemMedia,
  ItemTitle,
} from "@/components/ui/item"

// import { useRouter } from "next/router";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const getInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
//  const router = useRouter()
  
  return (
    <main className={`flex h-[100vh]  ${geistSans.variable} ${geistMono.variable} antialiased`}>
     
        {
            // sidebar
        }
        <div className={`w-[25%] px-[15px] pt-[25px] bg-black h-[100%]`} >
          <div>
          <h2 className={`text-3xl text-white font-bold ${getInter.className} uppercase  `}>Admin Console</h2>
          <p className={`text-lg text-white ${getInter.className} font-normal`} >System root</p>
          </div>
          

            {/* <div className={`flex items-center mb-[30px]`}>
                <Avatar className="w-[70px] h-[70px] mr-[10px]">
                    <AvatarImage
                    src="https://github.com/shadcn.png"
                    alt="@shadcn"
                    className="grayscale "
                    />
                    <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                    <h2 className={"text-white text-2xl flex gap-[5px] items-center font-bold mb-[10px]"}>John Doe <BadgeCheckIcon color="#3498db" className="size-5" /></h2> 
                    <div className={`flex gap-[10px]`} >
                        <Badge className={`text-lg`} variant="secondary">Administrator</Badge>
                        <Badge className={`text-white text-lg`} variant="outline">Edit</Badge>
                    </div>
                </div>
            </div> */}
  


    <div className="flex w-full max-w-md flex-col mt-4 gap-1">
      <Item className={`bg-transparent text-black hover:!text-black bg-[#dfe4ea] hover:!bg-[#dfe4ea] rounded-full`} variant="default" size="sm" asChild>
        <a href="#">
          <ItemMedia>
            <Mail className="size-5" />
          </ItemMedia>
          <ItemContent>
            <ItemTitle>Message</ItemTitle>
          </ItemContent>
          <ItemActions>
            <ChevronRightIcon className="size-4" />
          </ItemActions>
        </a>
      </Item>
      <Item className={`bg-transparent text-white hover:!text-black hover:!bg-[#dfe4ea] rounded-full`} variant="default" size="sm" asChild>
        <a href="#">
          <ItemMedia>
            <Newspaper className="size-5" />
          </ItemMedia>
          <ItemContent>
            <ItemTitle>Subscribers</ItemTitle>
          </ItemContent>
          <ItemActions>
            <ChevronRightIcon className="size-4" />
          </ItemActions>
        </a>
      </Item>
      <Item className={`bg-transparent text-white hover:!text-black hover:!bg-[#dfe4ea] rounded-full`} variant="default" size="sm" asChild>
        <a href="#">
          <ItemMedia>
            <Blocks className="size-5" />
          </ItemMedia>
          <ItemContent>
            <ItemTitle>Post</ItemTitle>
          </ItemContent>
          <ItemActions>
            <ChevronRightIcon className="size-4" />
          </ItemActions>
        </a>
      </Item>
      <Item className={`bg-transparent text-white hover:!text-black hover:!bg-[#dfe4ea] rounded-full`} variant="default" size="sm" asChild>
        <a href="#">
          <ItemMedia>
            <TextWrap className="size-5" />
          </ItemMedia>
          <ItemContent>
            <ItemTitle>Content</ItemTitle>
          </ItemContent>
          <ItemActions>
            <ChevronRightIcon className="size-4" />
          </ItemActions>
        </a>
      </Item>
      <Item className={`bg-transparent text-white hover:!text-black hover:!bg-[#dfe4ea] rounded-full`} variant="default" size="sm" asChild>
        <a href="#">
          <ItemMedia>
            <Settings className="size-5" />
          </ItemMedia>
          <ItemContent>
            <ItemTitle>Settings</ItemTitle>
          </ItemContent>
          <ItemActions>
            <ChevronRightIcon className="size-4" />
          </ItemActions>
        </a>
      </Item>
    </div>

        </div>
        <div className={`w-[75%] h-[100%]`} >
          <div className={`p-[15px] w-full bg-[#f1f2f6] `}>
              <h1 className={`text-3xl font-bold `}>Dashboard</h1>
            </div>
            <div className={`p-[15px] w-full  `}>
              {children}
            </div>
          
          </div>
      
    </main>
  );
}
