
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Header from "@/components/header";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "@/components/footer";

import { loadingEffect } from "@/lib/module";
import TopBar from "@/components/module/topBar";
// import { useRouter } from "next/router";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
//  const router = useRouter()
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {
          // router.pathname === "/admin" ? null : (<><TopBar />  <Header /></>)
        }
        <TopBar />
        <Header />
        {children}
        {
          // router.pathname === "/admin" ? null : <Footer />
        }
        <Footer />
      </body>
    </html>
  );
}
